name: go setup

on: 
  push:
    branches: [main]

jobs:
  my-job:
    name: My job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      run: |
        echo Hello world
    - name: List folders/files in vm
      run: |
        ls -lAhFa

