name: go setup

on: 
  push:
    branches: [main]

jobs:
  job1:
    name: Setup Go 1.16.4 in ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      run: |
        echo Hello world
        
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3
      with: 
        go-version: 1.16.4
        
    - name: Check Go installation and version
      run: go version
    
    - name: Checkout codes
      uses: actions/checkout@v2.3.4
      
    - name: List folders/files in root folder
      run: |
        ls -lAhFa
