name: go setup

on: 
  push:
    branches: [main]

jobs:
  builds:
    name: Setup Go 1.16.4 in ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      run: |
        echo Hello world
        
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3
      with: 
        go-version: 1.16.4
        
    - name: Check Go installation and version
      run: go version
        
  checkout:
    name: Checkout files from repo to vm
    needs: builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v2.3.4
      
      - name: List folders/files in root folder
        run: |
          ls -lAhFa

  test:
    name: Test code
    if: success()
    needs: [builds, checkout] 
    runs-on: ubuntu-latest
    steps:
      - name: mod init
        run: go mod init CI-tutorial
      - name: mod tidy
        run: go mod tidy 
      - name: run go test 
        run: |
          go mod init
          go test -v
    
