name: go setup

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  helloWorld:
    name: Hello world eg
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      run: |
        echo Hello world
        
  checkoutPrivate:
    name: Checkout private repo eg
    runs-on: ubuntu-latest
    steps:
    - name: Checkout private tools
      uses: actions/checkout@v2
      with:
        repository: lowkh2/GoSchoolRemoteExample
        token: ${{ secrets.GO_REMOTE_TUTORIAL }} 
        path: remoteRepo   
    - name: Check files
      run: |
        ls -lAhFa
        cd remoteRepo
        ls -lAhFa
        cd ..
        
  gotest:
    name: Testing in vm
    runs-on: ubuntu-latest
    steps:   
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3
      with: 
        go-version: 1.16.4
    - name: Check Go installation and version
      run: go version
    - name: Checkout codes
      uses: actions/checkout@v2.3.4
    - name: List folders/files in root folder
      run: |
        ls -lAhFa
        
    - name: Install go testing dependencies
      run: |
        go get github.com/franela/goblin
        go get github.com/tebeka/go2xunit
        go mod tidy
        
    - name: Run test
      #run test and converts output to .xml file
      run: |
        go test -v
        go test -v | go2xunit -output report.xml
        ls -lAhFa

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: report.xml
        
    - if: ${{failure()}}
      name: Create Issue Action
      uses: nashmaniac/create-issue-action@v1.1
      with:
         # Title of the issue
        title: Build fail
        # Token of the user that creates the issue
        token:  ${{secrets.GITHUB_token}}
        # Labels of the issue
        labels: workflow-failed
        # Assignees of the issue
        assignees: ${{github.actor}}
        # Body of the issue
        body: workflow failed for commit ${{github.sha}}
        
    - name: send failure message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: Fail to push code
        
    - if: ${{ success() }}
      name: Create download directory
      run: mkdir downloads
      
    - name: Prepare Documents
      run: |
        mv report.xml ./downloads
        
    - if: ${{ success() }}
      name: Prepare artifacts
      uses: actions/upload-artifact@v2
      with:
        name: assetDocuments
        path: downloads
        
    - if: ${{ success() }}
      name: Download Content
      uses: actions/download-artifact@v2
      with:
        name: assetDocuments
    
    - if: ${{ success() }}
      name: send success message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: Successfully push code
